export const APP_NAME = 'AuraStream';

export const GENRE_ITEMS = [
  'Electronic',
  'Lo-Fi',
  'Synthwave',
  'Pop',
  'Hip-Hop',
  'R&B',
  'Rock',
  'Indie',
  'Ambient',
  'Jazz',
  'Classical',
  'Acoustic',
  'Metal',
];

export const MOOD_CATEGORIES = [
  { id: 'focus', title: 'Deep Focus', color: 'from-blue-600 to-indigo-950', query: 'focus ambient instrumental' },
  { id: 'chill', title: 'Midnight Chill', color: 'from-purple-600 to-violet-950', query: 'chill lofi beats night vibes' },
  { id: 'workout', title: 'High Energy / Workout', color: 'from-red-600 to-rose-950', query: 'workout high energy workout music' },
  { id: 'party', title: 'Weekend Party', color: 'from-pink-600 to-fuchsia-950', query: 'party hits club dance music' },
  { id: 'sleep', title: 'Sleep & Calm', color: 'from-cyan-700 to-slate-950', query: 'sleep ambient soundscapes' },
  { id: 'gaming', title: 'Cyberpunk & Gaming', color: 'from-emerald-600 to-teal-950', query: 'synthwave cyberpunk gaming soundtrack' },
];

export const CURATED_TRACKS = [
  {
    id: '5qap5aO4i9A',
    youtube_id: '5qap5aO4i9A',
    title: 'lofi hip hop radio - beats to relax/study to',
    artist: 'Lofi Girl',
    duration: 180,
    thumbnail_url: 'https://i.ytimg.com/vi/5qap5aO4i9A/hqdefault.jpg',
    genre: 'Lo-Fi',
    views: 75000000,
  },
  {
    id: '4xDzrJKXOOY',
    youtube_id: '4xDzrJKXOOY',
    title: 'SYNTHWAVE RADIO - chill synth / retro / electro',
    artist: 'Lofi Girl - Synthwave',
    duration: 210,
    thumbnail_url: 'https://i.ytimg.com/vi/4xDzrJKXOOY/hqdefault.jpg',
    genre: 'Synthwave',
    views: 32000000,
  },
  {
    id: '1G4isv_Fylg',
    youtube_id: '1G4isv_Fylg',
    title: 'Midnight City',
    artist: 'M83',
    duration: 244,
    thumbnail_url: 'https://i.ytimg.com/vi/1G4isv_Fylg/hqdefault.jpg',
    genre: 'Electronic',
    views: 450000000,
  },
  {
    id: 'NF-kLy44Hls',
    youtube_id: 'NF-kLy44Hls',
    title: 'Starboy (feat. Daft Punk)',
    artist: 'The Weeknd',
    duration: 231,
    thumbnail_url: 'https://i.ytimg.com/vi/NF-kLy44Hls/mqdefault.jpg',
    genre: 'R&B',
    views: 2400000000,
  },
  {
    id: '4NRXx6U8ABQ',
    youtube_id: '4NRXx6U8ABQ',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    duration: 200,
    thumbnail_url: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/mqdefault.jpg',
    genre: 'Pop',
    views: 1200000000,
  },
  {
    id: 'kXYiU_JCYtU',
    youtube_id: 'kXYiU_JCYtU',
    title: 'Numb',
    artist: 'Linkin Park',
    duration: 187,
    thumbnail_url: 'https://i.ytimg.com/vi/kXYiU_JCYtU/mqdefault.jpg',
    genre: 'Rock',
    views: 2100000000,
  },
  {
    id: 'hT_nvWreIhg',
    youtube_id: 'hT_nvWreIhg',
    title: 'Counting Stars',
    artist: 'OneRepublic',
    duration: 257,
    thumbnail_url: 'https://i.ytimg.com/vi/hT_nvWreIhg/mqdefault.jpg',
    genre: 'Pop',
    views: 3900000000,
  },
  {
    id: 'SlPhMPnQ58k',
    youtube_id: 'SlPhMPnQ58k',
    title: 'Memories (feat. Kid Cudi)',
    artist: 'David Guetta',
    duration: 212,
    thumbnail_url: 'https://i.ytimg.com/vi/SlPhMPnQ58k/mqdefault.jpg',
    genre: 'Electronic',
    views: 520000000,
  },
  {
    id: 'L_LUpnjgPso',
    youtube_id: 'L_LUpnjgPso',
    title: 'Resonance',
    artist: 'HOME',
    duration: 212,
    thumbnail_url: 'https://i.ytimg.com/vi/L_LUpnjgPso/mqdefault.jpg',
    genre: 'Synthwave',
    views: 120000000,
  },
  {
    id: 'ApXoWvfEYVU',
    youtube_id: 'ApXoWvfEYVU',
    title: 'Sunflower (Spider-Man: Into the Spider-Verse)',
    artist: 'Post Malone, Swae Lee',
    duration: 158,
    thumbnail_url: 'https://i.ytimg.com/vi/ApXoWvfEYVU/hqdefault.jpg',
    genre: 'Hip-Hop',
    views: 2200000000,
  },
  {
    id: 'RgKAFK5djSk',
    youtube_id: 'RgKAFK5djSk',
    title: 'See You Again (feat. Charlie Puth)',
    artist: 'Wiz Khalifa',
    duration: 237,
    thumbnail_url: 'https://i.ytimg.com/vi/RgKAFK5djSk/mqdefault.jpg',
    genre: 'Hip-Hop',
    views: 6000000000,
  },
  {
    id: 'JGwWNGJdvx8',
    youtube_id: 'JGwWNGJdvx8',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    duration: 234,
    thumbnail_url: 'https://i.ytimg.com/vi/JGwWNGJdvx8/mqdefault.jpg',
    genre: 'Pop',
    views: 6200000000,
  },
];

